---
# tasks file for docker-installer
# Modified by Ronier Rodríguez
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install CentOS packages for Docker
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - device-mapper-persistent-data
    - lvm2

- name: Download CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install Docker Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add user to Docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install python-pip 
  package:
    name: python-pip
    state: latest

- name: Install Docker SDK through pip (Required by docker_ modules)
  pip:
    name: docker
    state: latest
    